### ISSUE TITLE
F2F low-diffusion filesharing app

### ISSUE THREAD

**Issue by MichaelMure** [MichaelMure/Arbore-qt#1]
Original link: https://github.com/ipfs/go-ipfs/issues/961

I would really like to see happen a friend-to-friend filesharing app with the following caracteristics:
- targeted for private/low diffusion data between people that know each-others. Main use case: friends want to share between each-others their holidays pictures.
- low friction: it should be as easy as possible
- encryption should be used to maintain privacy and control the diffusion of the data

The underlying goal is to reduce the need to use solution like Facebook, Dropbox, Drive... for file/pictures exchange that should be kept private. Also [this](https://xkcd.com/949/).

IPFS seems to be the perfect backend for this project. What I envision is a thin GUI layer that provide the low-friction caracteristics. Most of the actual feature would be in IPFS. Here is the issues that needs to be resolved for this project to happen:
- [ ] jbenet/go-ipfs/issues/875 : avoid duplicating files added to ipfs, ie having ipfs track and share files that are directly on disk, not copied in the datastore
- [ ] jbenet/go-ipfs/issues/930 : API access to current download 
- [ ] ipfs/specs/issues/3 : keystore, encryption, signing and key sharing support
- [ ] jbenet/ipfs/issues/45 : having a node keypair and an identity keypair
- [ ] pub/sub system : @cryptix mentionned this system as a way for user to notify the receiver that somethng was shared to them, need more details

Optional:
- [ ] jbenet/go-ipfs/issues/920 Need statistics on what content is being uploaded
- [ ] jbenet/go-ipfs/issues/826 Private keys should be encrypted

On a side note, a problem that arise with low-diffusion filesharing is that sender and receivers need to be online at the same time. The future Filecoin seems to be a good solution to mitigate this problem as the sender could incentive other nodes to replicate and hold the encrypted blob online while he is offline.
